### ISSUE TITLE
After installing running in to error

### ISSUE THREAD

**Issue by ikswokjam** [notify-run/notify-run-server#4]
Traceback (most recent call last):
  File "/usr/local/bin/notify-run-server", line 6, in <module>
    from notify_run_server.app import main
  File "/usr/local/lib/python2.7/dist-packages/notify_run_server/__init__.py", line 1, in <module>
    from notify_run_server.app import app
  File "/usr/local/lib/python2.7/dist-packages/notify_run_server/app.py", line 7, in <module>
    from notify_run_server.model import NoSuchChannel, NotifyModel
  File "/usr/local/lib/python2.7/dist-packages/notify_run_server/model.py", line 21
    def register_channel(self, meta: dict) -> str:
                                   ^
SyntaxError: invalid syntax

Hope it helps or maybe i did something wrong. 

Groetjes

**Comment by paulgb** [comment]
Hi, are you using Python 2? The client still supports Python 2.x but the server only supports Python 3.
